name: Create Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        name: "FuelTime ${{ github.ref_name }}"
        body: |
          #  FuelTime ${{ github.ref_name }}
          
          ##  Quick Deploy
          
          `yaml
          services:
            fueltime:
              image: ghcr.io/${{ github.repository_owner }}/fueltime:${{ github.ref_name }}
              container_name: fueltime-app
              ports:
                - "5000:5000"
              restart: unless-stopped
          `
          
          ##  Features
          - Fuel sheet management with PDF generation
          - Timesheet management with auto-fill calendar  
          - Digital signatures (canvas + file upload)
          - Production-ready Docker deployment
          
          Complete setup instructions in README.md
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
